
#define LISTENING_STATE 0
#define CAPTURING_STATE 1
#define MOVING_STATE 2
#define TURNING_STATE 3
#define VARIABLE_CHANGE_STATE 4
#define PAUSED_STATE 5
#define HOMING_STATE 6
#define TESTING_SEQUENCE_STATE 7
#define STOPPING_STATE 8



